spring:
  application:
    name: bank-service
  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:file:../.env[.properties]"
      - "optional:file:../../.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET}
    ttl: ${JWT_TTL:PT12H}

fraud:
  url: ${FRAUD_URL:http://localhost:8000}

server:
  port: ${SERVER_PORT:8080}
