services:

  bank-db:
    image: postgres:17.2-alpine
    container_name: bank-db
    environment:
      POSTGRES_USER: ${BANK_DB_USER}
      POSTGRES_PASSWORD: ${BANK_DB_PASSWORD}
      POSTGRES_DB: ${BANK_DB_NAME}
    ports:
      - "${BANK_DB_PORT}:5432"
    volumes:
      - bank-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  fraud-detection:
    build: ./apps/fraud-detection
    container_name: fraud-detection
    environment:
      FRAUD_AMOUNT_THRESHOLD: ${FRAUD_AMOUNT_THRESHOLD:-10000}
    ports:
      - "8000:8000"

volumes:
  bank-db-data:
